[tool.poetry]
name = "psrdb"
version = "0.1.0"
description = "CLI for pulsars.org.au"
authors = ["GWDC"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]
pytest = "^7.3.1"

[tool.poetry.scripts]
psrdb = "scripts.psrdb:main"
"ingest_ptuse_folded.py" = "scripts.ingest_ptuse_folded:main"
"ingest_ptuse_search.py" = "scripts.ingest_ptuse_search:main"
"ingest.py" = "scripts.ingest:main"
"remove_fluxcals.py" = "scripts.remove_fluxcals:main"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
